name = "nocca"
main = "worker/index.js"
compatibility_date = "2024-01-01"


[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatRoom"


[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]


[[d1_databases]]
binding = "DB"
database_name = "nocca-db"
database_id = "YOUR_DB_ID"
